# 05.Numpy

In [1]:
import numpy as np

## 행렬 연산(np.array)

In [2]:
#행렬으로 표현해준다.
A = np.array([ [1,0], [0,1] ])
B = np.array([ [1,1], [1,0] ])

print(A+B)

[[2 1]
 [1 1]]


In [3]:
# 일반 list의 경우 단순히 이어붙이기만 한다.
A_list = [[1,0], [0,1]]
B_list = [[1,1], [1,0]]
A_list+B_list

[[1, 0], [0, 1], [1, 1], [1, 0]]

In [4]:
A = np.array([1,2,3])
B = np.array([4,5,6])

print("A == ", A, "B == ", B)
print("A.shape == ", A.shape, "B.shape == ", B.shape)
print("dimension of A : ", A.ndim, "dimension of B : ", B.ndim)

A ==  [1 2 3] B ==  [4 5 6]
A.shape ==  (3,) B.shape ==  (3,)
dimension of A :  1 dimension of B :  1


In [5]:
print(A+B)
print(A-B)
print(A*B)
print(A/B)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [6]:
A = np.array([[1,2,3], [4,5,6]]) #하나의 행을 하나의 대괄호로 표현함
B = np.array([[3,3,3], [3,3,3]])

print("A.shape:", A.shape, "B.shape:", B.shape)
print("dimension of A : ", A.ndim, "dimension of B : ", B.ndim)
print(A*B)

A.shape: (2, 3) B.shape: (2, 3)
dimension of A :  2 dimension of B :  2
[[ 3  6  9]
 [12 15 18]]


## 행, 열 변환

In [7]:
C = np.array([1,2,3])
print(C.shape)
C = C.reshape(1,3)
print(C.shape)

(3,)
(1, 3)


In [8]:
A = np.array([[1,2,3], [4,5,6]])
print(A) #2행 3열 행렬
print("행우선 변환 : ")
print(np.reshape(A, (3, 2))) #행우선 변환
print("열우선 변환 : ")
print(np.reshape(A, (3, 2), order='F')) #열우선 저장

[[1 2 3]
 [4 5 6]]
행우선 변환 : 
[[1 2]
 [3 4]
 [5 6]]
열우선 변환 : 
[[1 5]
 [4 3]
 [2 6]]


## 행렬 곱

In [9]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[3,3], [3,3], [3,3]])
print(A.shape, B.shape)
C = np.dot(A,B) #A행의 열과 B행의 행이 같아야 행렬곱이 가능하다. dot이 행렬곱임.
#행렬곱의 결과는 A행의 행XB행의 열 이다.
print(C)

(2, 3) (3, 2)
[[18 18]
 [45 45]]


## Broadcast(사칙연산에만 적용)
'사칙연산'에 대해서(not 행렬 곱) 두 개의 행렬 크기가 다르더라도, 사칙연산을 수행할 수 있게 해줌.

In [10]:
A = np.array([[1,2],[3,4]])
B = 5

print(A+B)
# [1 2] + 5 = [1, 2] + [5, 5]
# [3 4]      [3, 4] + [5, 5]

[[6 7]
 [8 9]]


In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([-1,-2])
print(A+B)

# [1 2] + [-1,-2] = [1, 2] + [-1, -2] = [0, 0]
# [3 4]            [3, 4] + [-1, -2] = [2, 2]

[[0 0]
 [2 2]]


## 전치행렬
행과 열을 바꿔줌
A[i,j]를 A[j,i]로 바꿔줌

In [12]:
A = np.array([[1,2], [3,4], [5,6]])
B = A.T
print(A)
print("A shape : ",A.shape)
print()
print(B)
print("B shape : ",B.shape)

[[1 2]
 [3 4]
 [5 6]]
A shape :  (3, 2)

[[1 3 5]
 [2 4 6]]
B shape :  (2, 3)


In [13]:
#vector에 Transpose를 하더라도 matrix로 변하지는 않는다.
C = np.array([1,2,3,4,5])
D = C.T
print(C)
print(D)

[1 2 3 4 5]
[1 2 3 4 5]


In [14]:
E = np.array([[1,2,3,4,5]])
F = E.T
print(E)
print(F)

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [15]:
#reshape를 통해 matrix로 변환후 전치가 가능함
G = np.array([1,2,3,4,5])
G = G.reshape(1,5)
print(G)
H = G.T
print(H)

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


## 행렬의 Indexing, slicing

In [16]:
A = np.array([10, 20, 30, 40, 50, 60]).reshape(3,2)
print(A)

[[10 20]
 [30 40]
 [50 60]]


In [17]:
print(A[0,0])
print(A[1,1])
print(A[2,0])

10
40
50


In [18]:
print(A[0:, -2:])

[[10 20]
 [30 40]
 [50 60]]


In [19]:
print(A[-1:, 0:])

[[50 60]]


In [20]:
print(A[:,:])

[[10 20]
 [30 40]
 [50 60]]


## numpy - iterator
행렬의 모든 원소에 access하는 경우

In [21]:
A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(A)
print(A.shape)

[[10 20 30 40]
 [50 60 70 80]]
(2, 4)


In [22]:
it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])
#행우선 접근
while not it.finished:
    idx = it.multi_index
    print(A[idx])
    it.iternext()

10
20
30
40
50
60
70
80


In [23]:
it.reset()
print(it.finished)

False


## concatenate
행렬에 행과 열을 추가함

In [26]:
A = np.array([[10, 20, 30], [40, 50, 60]])
print(A.shape)
print(A)

(2, 3)
[[10 20 30]
 [40 50 60]]


In [32]:
#vector는 행과 열을 구분하지 않기 때문에, reshape해줘야 기존의 행렬에 하나의 행을 추가할 수 있게 된다.
row_add = np.array([70, 80, 90]).reshape(1,3)
column_add = np.array([100, 200, 300]).reshape(3,1)

In [33]:
#axis : {0 : row, 1:column}
B = np.concatenate((A, row_add), axis=0)
print(B)
C = np.concatenate((B, column_add), axis=1)
print(C)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[ 10  20  30 100]
 [ 40  50  60 200]
 [ 70  80  90 300]]


## loadtxt
seperator로 구분된 파일에서 데이터를 읽기 위한 함수

In [41]:
import csv
import random
with open('test.csv', 'w', encoding='utf-8') as f:
    wr = csv.writer(f)
    for i in range(10):
        wr.writerow([random.randint(-100, 100), random.randint(-100, 100), random.randint(-100, 100), random.randint(-100, 100)])
        

In [43]:
loaded_data=np.loadtxt('test.csv', delimiter=',', dtype=np.float32)
print(loaded_data)

[[ 81.  29.  38.  25.]
 [-88.  66.   6.  61.]
 [-91. -17.  12. -27.]
 [  9.  -7. -36. -80.]
 [-81.  59. -99.  -4.]
 [-40.  94. -43.  64.]
 [-41. -76.  53.  66.]
 [ 29.  32.  -3.  89.]
 [ 72. -59. -37. -42.]
 [ 21.  63.   3. -61.]]
[[ 81.  29.  38.]
 [-88.  66.   6.]
 [-91. -17.  12.]
 [  9.  -7. -36.]
 [-81.  59. -99.]
 [-40.  94. -43.]
 [-41. -76.  53.]
 [ 29.  32.  -3.]
 [ 72. -59. -37.]
 [ 21.  63.   3.]]


In [45]:
x_data = loaded_data[:, 0:-1]
print(x_data)

[[ 81.  29.  38.]
 [-88.  66.   6.]
 [-91. -17.  12.]
 [  9.  -7. -36.]
 [-81.  59. -99.]
 [-40.  94. -43.]
 [-41. -76.  53.]
 [ 29.  32.  -3.]
 [ 72. -59. -37.]
 [ 21.  63.   3.]]


In [47]:
t_data = loaded_data[:, [-1]]
print(t_data.reshape(1, 10))

[[ 25.  61. -27. -80.  -4.  64.  66.  89. -42. -61.]]


## random
rand() : 0~1사이의 임의값

In [49]:
rand1 = np.random.rand()
rand2 = np.random.rand()
rand3 = np.random.rand()

print(rand1)
print(rand2)
print(rand3)

0.7935908975164804
0.49499262900101637
0.056229315015427495


## 다양한 수학함수

In [51]:
A = np.array([2, 4, 8, 16])
print(np.exp(A))
print(np.exp2(A))
print(np.sum(A))
print(np.average(A))
print(np.log(A))

[7.38905610e+00 5.45981500e+01 2.98095799e+03 8.88611052e+06]
[4.0000e+00 1.6000e+01 2.5600e+02 6.5536e+04]
30
7.5
[0.69314718 1.38629436 2.07944154 2.77258872]


## min, max, argmin, argmax

In [57]:
print("max :",np.max(A))
print("min :",np.min(A))
print("argmax :",np.argmax(A)) #index를 리턴해준다.
print("argmin :",np.argmin(A)) #

max : 16
min : 2
argmax : 3
argmin : 0


In [67]:
B = np.array([[4,2,6], [1,6,9]])
print(np.min(B, axis=0)) #각 열에서 최소값만 찾아서 벡터를 만들어줌
print(np.min(B, axis=1)) #각 행에서 최소값만 찾아서 벡터를 만들어줌 
print(np.max(B, axis=0)) #각 열에서 최대값만 찾아서 벡터를 만들어줌
print(np.max(B, axis=1)) #각 행에서 최대값만 찾아서 벡터를 만들어줌

[1 2 6]
[2 1]
[4 6 9]
[6 9]


In [68]:
print(np.argmin(B, axis=0)) #각 열에서 최소값만 찾아서 인덱스를 반환 (1행, 2행, 2행)에 max값이 존재함.
print(np.argmin(B, axis=1)) #각 행에서 최소값만 찾아서 인덱스를 반환
print(np.argmax(B, axis=0)) #각 열에서 최대값만 찾아서 인덱스를 반환
print(np.argmax(B, axis=1)) #각 행에서 최대값만 찾아서 인덱스를 반환

[1 0 0]
[1 0]
[0 1 1]
[2 2]


## ones, zeros

In [69]:
A_ones = np.ones([3,3])
A_zeros = np.zeros([3,3])
print(A_ones)
print(A_zeros)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
