# 05.Numpy

In [1]:
import numpy as np

## 행렬 연산(np.array)

In [2]:
#행렬으로 표현해준다.
A = np.array([ [1,0], [0,1] ])
B = np.array([ [1,1], [1,0] ])

print(A+B)

[[2 1]
 [1 1]]


In [3]:
# 일반 list의 경우 단순히 이어붙이기만 한다.
A_list = [[1,0], [0,1]]
B_list = [[1,1], [1,0]]
A_list+B_list

[[1, 0], [0, 1], [1, 1], [1, 0]]

In [4]:
A = np.array([1,2,3])
B = np.array([4,5,6])

print("A == ", A, "B == ", B)
print("A.shape == ", A.shape, "B.shape == ", B.shape)
print("dimension of A : ", A.ndim, "dimension of B : ", B.ndim)

A ==  [1 2 3] B ==  [4 5 6]
A.shape ==  (3,) B.shape ==  (3,)
dimension of A :  1 dimension of B :  1


In [5]:
print(A+B)
print(A-B)
print(A*B)
print(A/B)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [6]:
A = np.array([[1,2,3], [4,5,6]]) #하나의 행을 하나의 대괄호로 표현함
B = np.array([[3,3,3], [3,3,3]])

print("A.shape:", A.shape, "B.shape:", B.shape)
print("dimension of A : ", A.ndim, "dimension of B : ", B.ndim)
print(A*B)

A.shape: (2, 3) B.shape: (2, 3)
dimension of A :  2 dimension of B :  2
[[ 3  6  9]
 [12 15 18]]


## 행, 열 변환

In [7]:
C = np.array([1,2,3])
print(C.shape)
C = C.reshape(1,3)
print(C.shape)

(3,)
(1, 3)


In [8]:
A = np.array([[1,2,3], [4,5,6]])
print(A) #2행 3열 행렬
print("행우선 변환 : ")
print(np.reshape(A, (3, 2))) #행우선 변환
print("열우선 변환 : ")
print(np.reshape(A, (3, 2), order='F')) #열우선 저장

[[1 2 3]
 [4 5 6]]
행우선 변환 : 
[[1 2]
 [3 4]
 [5 6]]
열우선 변환 : 
[[1 5]
 [4 3]
 [2 6]]


## 행렬 곱

In [9]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[3,3], [3,3], [3,3]])
print(A.shape, B.shape)
C = np.dot(A,B) #A행의 열과 B행의 행이 같아야 행렬곱이 가능하다. dot이 행렬곱임.
#행렬곱의 결과는 A행의 행XB행의 열 이다.
print(C)

(2, 3) (3, 2)
[[18 18]
 [45 45]]


## Broadcast(사칙연산에만 적용)
'사칙연산'에 대해서(not 행렬 곱) 두 개의 행렬 크기가 다르더라도, 사칙연산을 수행할 수 있게 해줌.

In [10]:
A = np.array([[1,2],[3,4]])
B = 5

print(A+B)
# [1 2] + 5 = [1, 2] + [5, 5]
# [3 4]      [3, 4] + [5, 5]

[[6 7]
 [8 9]]


In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([-1,-2])
print(A+B)

# [1 2] + [-1,-2] = [1, 2] + [-1, -2] = [0, 0]
# [3 4]            [3, 4] + [-1, -2] = [2, 2]

[[0 0]
 [2 2]]


## 전치행렬
행과 열을 바꿔줌
A[i,j]를 A[j,i]로 바꿔줌

In [16]:
A = np.array([[1,2], [3,4], [5,6]])
B = A.T
print(A)
print("A shape : ",A.shape)
print()
print(B)
print("B shape : ",B.shape)

[[1 2]
 [3 4]
 [5 6]]
A shape :  (3, 2)

[[1 3 5]
 [2 4 6]]
B shape :  (2, 3)


In [18]:
#vector에 Transpose를 하더라도 matrix로 변하지는 않는다.
C = np.array([1,2,3,4,5])
D = C.T
print(C)
print(D)

[1 2 3 4 5]
[1 2 3 4 5]


In [19]:
E = np.array([[1,2,3,4,5]])
F = E.T
print(E)
print(F)

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [23]:
#reshape를 통해 matrix로 변환후 전치가 가능함
G = np.array([1,2,3,4,5])
G = G.reshape(1,5)
print(G)
H = G.T
print(H)

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


## 행렬의 Indexing, slicing

In [24]:
A = np.array([10, 20, 30, 40, 50, 60]).reshape(3,2)
print(A)

[[10 20]
 [30 40]
 [50 60]]


In [29]:
print(A[0,0])
print(A[1,1])
print(A[2,0])

10
40
50


In [44]:
print(A[0:, -2:])

[[10 20]
 [30 40]
 [50 60]]


In [49]:
print(A[-1:, 0:])

[[50 60]]


In [50]:
print(A[:,:])

[[10 20]
 [30 40]
 [50 60]]


## numpy - iterator
행렬의 모든 원소에 access하는 경우

In [52]:
A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(A)
print(A.shape)

[[10 20 30 40]
 [50 60 70 80]]
(2, 4)


In [54]:
it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])
#행우선 접근
while not it.finished:
    idx = it.multi_index
    print(A[idx])
    it.iternext()

10
20
30
40
50
60
70
80


In [58]:
it.reset()
print(it.finished)

False
