# 05.Numpy

In [13]:
import numpy as np

## 행렬 연산(np.array)

In [29]:
#행렬으로 표현해준다.
A = np.array([ [1,0], [0,1] ])
B = np.array([ [1,1], [1,0] ])

print(A+B)

[[2 1]
 [1 1]]


array([[1, 1],
       [1, 0]])

In [21]:
# 일반 list의 경우 단순히 이어붙이기만 한다.
A_list = [[1,0], [0,1]]
B_list = [[1,1], [1,0]]
A_list+B_list

[[1, 0], [0, 1], [1, 1], [1, 0]]

In [30]:
A = np.array([1,2,3])
B = np.array([4,5,6])

print("A == ", A, "B == ", B)
print("A.shape == ", A.shape, "B.shape == ", B.shape)
print("dimension of A : ", A.ndim, "dimension of B : ", B.ndim)

A ==  [1 2 3] B ==  [4 5 6]
A.shape ==  (3,) B.shape ==  (3,)
dimension of A :  1 dimension of B :  1


In [34]:
print(A+B)
print(A-B)
print(A*B)
print(A/B)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [37]:
A = np.array([[1,2,3], [4,5,6]]) #하나의 행을 하나의 대괄호로 표현함
B = np.array([[3,3,3], [3,3,3]])

print("A.shape:", A.shape, "B.shape:", B.shape)
print("dimension of A : ", A.ndim, "dimension of B : ", B.ndim)
print(A*B)

A.shape: (2, 3) B.shape: (2, 3)
dimension of A :  2 dimension of B :  2
[[ 3  6  9]
 [12 15 18]]


## 행, 열 변환

In [40]:
C = np.array([1,2,3])
print(C.shape)
C = C.reshape(1,3)
print(C.shape)

(3,)
(1, 3)


In [71]:
A = np.array([[1,2,3], [4,5,6]])
print(A) #2행 3열 행렬
print("행우선 변환 : ")
print(np.reshape(A, (3, 2))) #행우선 변환
print("열우선 변환 : ")
print(np.reshape(A, (3, 2), order='F')) #열우선 저장

[[1 2 3]
 [4 5 6]]
행우선 변환 : 
[[1 2]
 [3 4]
 [5 6]]
열우선 변환 : 
[[1 5]
 [4 3]
 [2 6]]


## 행렬 곱

In [74]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[3,3], [3,3], [3,3]])
print(A.shape, B.shape)
C = np.dot(A,B) #A행의 열과 B행의 행이 같아야 행렬곱이 가능하다. dot이 행렬곱임.
#행렬곱의 결과는 A행의 행XB행의 열 이다.
print(C)

(2, 3) (3, 2)
[[18 18]
 [45 45]]


## 행렬곱 : Broadcast
'사칙연산'에 대해서(not 행렬 곱) 두 개의 행렬 크기가 다르더라도, 사칙연산을 수행할 수 있게 해줌.

In [75]:
A = np.array([[1,2],[3,4]])
B = 5

print(A+B)
# [1 2] + 5 = [1, 2] + [5, 5]
# [3 4]      [3, 4] + [5, 5]

[[6 7]
 [8 9]]


In [78]:
A = np.array([[1,2],[3,4]])
B = np.array([-1,-2])
print(A+B)

# [1 2] + [-1,-2] = [1, 2] + [-1, -2] = [0, 0]
# [3 4]            [3, 4] + [-1, -2] = [2, 2]

[[0 0]
 [2 2]]
