# 8. Simple Regression

In [42]:
import numpy as np

#초기 데이터
x_data = np.array([1,2,3,4,5]).reshape(5,1)
t_data = np.array([2,3,4,5,6]).reshape(5,1)

In [2]:
#임의의 W와 b값을 rand함수로 고른다.
W = np.random.rand(1,1)
b = np.random.rand(1)
print("W = ", W, "W.shape = ", W.shape, "b = ", b, "b.shape = ", b.shape)

W =  [[0.79944403]] W.shape =  (1, 1) b =  [0.0294241] b.shape =  (1,)


In [27]:
#손실함수
def error_val(x, t):
    y = np.dot(x, W) + b
    
    return (np.sum(((t-y)**2)/(len(x))))

#손실함수
def loss_func(x, t):
    y = np.dot(x, W) + b
    
    return (np.sum(((t-y)**2)/(len(x))))

In [4]:
#다변수 함수를 미분하는 함수
def numerical_derivative(f, x):
    delta_x = 1e-5
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    #각 변수들에 대해서 다른 값은 상수로 두고, 미분을 한다.
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val)+delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1-fx2)/(2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [5]:
#학습된 프로그램으로 y를 예측
def predict(x):
    y = np.dot(x,W)+b
    return y

In [11]:
learning_rate = 1e-2
f = lambda x : loss_func(x_data, t_data)
print(' initial error value = ', error_val(x_data, t_data), '\n initial W =', W, '\n', 'initial b = ', b)

for step in range(8001):
    W -= learning_rate*numerical_derivative(f, W)
    b -= learning_rate*numerical_derivative(f, b)
    
    if(step % 400 == 0):
        #error_val는 업데이트 된 W와 b로 오차를 계산해 준다.
        print('step = ', step, 'error_value = ', error_val(x_data, t_data), 'W = ', W, 'b = ', b)

 initial error value =  9.949449051065161e-05 
 initial W = [[1.00647733]] 
 initial b =  [0.97662049]
step =  0 error_value =  9.88123401548469e-05 W =  [[1.00645509]] b =  [0.97670078]
step =  400 error_value =  6.304811477815641e-06 W =  [[1.00163054]] b =  [0.99411466]
step =  800 error_value =  4.0228424616430366e-07 W =  [[1.00041187]] b =  [0.99851337]
step =  1200 error_value =  2.566811319902893e-08 W =  [[1.00010404]] b =  [0.99962448]
step =  1600 error_value =  1.6377773713039007e-09 W =  [[1.00002628]] b =  [0.99990514]
step =  2000 error_value =  1.0449987878634017e-10 W =  [[1.00000664]] b =  [0.99997604]
step =  2400 error_value =  6.667710066913286e-12 W =  [[1.00000168]] b =  [0.99999395]
step =  2800 error_value =  4.2543932135454554e-13 W =  [[1.00000042]] b =  [0.99999847]
step =  3200 error_value =  2.714554386966878e-14 W =  [[1.00000011]] b =  [0.99999961]
step =  3600 error_value =  1.7320461423475713e-15 W =  [[1.00000003]] b =  [0.9999999]
step =  4000 error_

In [14]:
predict(500)

array([[501.]])

In [43]:
loaded_data = np.loadtxt('./test01.csv', delimiter=',', dtype=np.float32)

x_data = loaded_data[ : , 0:-1]
t_data = loaded_data[ : , -1:]

In [50]:
W = np.random.rand(3,1) #3행 1열 행렬
b = np.random.rand(1)
print("W = ", W, "W.shape = ", W.shape, "b = ", b, "b.shape = ", b.shape)


W =  [[0.82789623]
 [0.93846849]
 [0.3312552 ]] W.shape =  (3, 1) b =  [0.90173755] b.shape =  (1,)


In [64]:
W = np.random.rand(3,1) #3행 1열 행렬
b = np.random.rand(1)
print("W = ", W, "W.shape = ", W.shape, "b = ", b, "b.shape = ", b.shape)

learning_rate = 1e-5
f = lambda x : loss_func(x_data, t_data)
print(' initial error value = ', error_val(x_data, t_data), '\n initial W =', W, '\n', 'initial b = ', b)

for step in range(18001):
    W -= learning_rate*numerical_derivative(f, W)
    b -= learning_rate*numerical_derivative(f, b)
    
    if(step % 400 == 0):
        #error_val는 업데이트 된 W와 b로 오차를 계산해 준다.
        print('step = ', step, 'error_value = ', error_val(x_data, t_data), 'W = \n', W, 'b = ', b)

W =  [[0.14739534]
 [0.26532433]
 [0.45938322]] W.shape =  (3, 1) b =  [0.87014623] b.shape =  (1,)
 initial error value =  8470.2569123299 
 initial W = [[0.14739534]
 [0.26532433]
 [0.45938322]] 
 initial b =  [0.87014623]
step =  0 error_value =  3137.1148029442124 W = 
 [[0.29434383]
 [0.41305875]
 [0.61073976]] b =  [0.87125247]
step =  400 error_value =  7.872021701065158 W = 
 [[0.50576216]
 [0.6181546 ]
 [0.88520686]] b =  [0.87246947]
step =  800 error_value =  7.43269735204714 W = 
 [[0.4908468 ]
 [0.59842249]
 [0.91899144]] b =  [0.8719249]
step =  1200 error_value =  7.1170402971196305 W = 
 [[0.47745927]
 [0.58238396]
 [0.94768222]] b =  [0.87134339]
step =  1600 error_value =  6.889444916101928 W = 
 [[0.46543648]
 [0.56939174]
 [0.97207017]] b =  [0.87073051]
step =  2000 error_value =  6.724707421957266 W = 
 [[0.45463372]
 [0.55890833]
 [0.99282111]] b =  [0.87009094]
step =  2400 error_value =  6.604958728005352 W = 
 [[0.4449225 ]
 [0.55048771]
 [1.01049572]] b =  [0

In [66]:
predict(np.array([100,98,81]))

array([178.8633459])