# 9.Logistic Regression

## 1단계 : 데이터 전처리

In [1]:
import numpy as np

x_data = np.array([2,4,6,8,10,12,14,16,18,20]).reshape(10,1)
t_data = np.array([0,0,0,0,0,0,1,1,1,1]).reshape(10,1)


## 2단계 : Z=Wx+b에서 W, b를 랜덤 값으로 저장

In [2]:
W = np.random.rand(1,1) #1행 1열의 값을 생성. 행렬 곱을 위해
b = np.random.rand(1) #행렬과의 연산을 위해서 rand에 인자로 1을 전달 1행

## 3단계 : 손실함수 작성

In [3]:
# 1/(1+e^-x)
def sigmoid(x):
    return 1/(1+np.exp(-x))


def loss_func(x, t):
    #log값이 무한대로 발산하는 것을 방지하기 위함.
    delta = 1e-7
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    return -np.sum((t*np.log(y+delta))+((1-t)*np.log(1-y+delta)))

## 3-2단계 : 기타 함수 작성

In [4]:
def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    #각 변수에 대해서 편미분을 하는 부분
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val)+delta_x
        fx1 = f(x)
        
        x[idx] = float(tmp_val)-delta_x
        fx2 = f(x)
        grad[idx] = (fx1-fx2)/(2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

def error_value(x, t):
   #log값이 무한대로 발산하는 것을 방지하기 위함.
    delta = 1e-7
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    return -np.sum((t*np.log(y+delta))+((1-t)*np.log(1-y+delta)))

def predict(x):
    z = np.dot(x,W)+b
    y = sigmoid(z)
    
    if(y>0.5):
        result = 1
    else:
        result = 0
        
    return y, result

## 4단계 : 학습률 알파를 설정, 가중치 W와 바이어스 b를 구한다

In [13]:
learning_rate = 1e-2
f = lambda x : loss_func(x_data, t_data)
print('initial error value : ', error_value(x_data, t_data))
print('initial W : ', W)
print('initial b : ', b)

for step in range(10001):
    W -= learning_rate*numerical_derivative(f, W)
    b -= learning_rate*numerical_derivative(f, b)
    
    if(step % 400 == 0):
        print('step : ', step, '\nerror_value : ', error_value(x_data, t_data))
        print('W : ', W, 'b : ', b,'\n')

initial error value :  0.43796761410345064
initial W :  [[1.47724995]]
initial b :  [-19.0990181]
step :  0 
error_value :  0.4379556460238551
W :  [[1.47727644]] b :  [-19.0993636] 

step :  400 
error_value :  0.43322950992835496
W :  [[1.48780442]] b :  [-19.23667576] 

step :  800 
error_value :  0.4286217279737081
W :  [[1.49820023]] b :  [-19.37225585] 

step :  1200 
error_value :  0.4241272554506668
W :  [[1.50846791]] b :  [-19.50615677] 

step :  1600 
error_value :  0.4197413562461707
W :  [[1.51861125]] b :  [-19.63842874] 

step :  2000 
error_value :  0.4154595784232432
W :  [[1.52863391]] b :  [-19.76911954] 

step :  2400 
error_value :  0.41127773214969177
W :  [[1.53853932]] b :  [-19.89827464] 

step :  2800 
error_value :  0.40719186971139726
W :  [[1.54833078]] b :  [-20.02593735] 

step :  3200 
error_value :  0.4031982673800039
W :  [[1.55801144]] b :  [-20.15214899] 

step :  3600 
error_value :  0.39929340893392445
W :  [[1.56758429]] b :  [-20.27694896] 

step

## 5단계 : 학습한 W, b를 활용해서 예측

In [14]:
predict(14)

(array([[0.85877926]]), 1)

In [16]:
predict(11)

(array([[0.03492168]]), 0)

In [18]:
predict(18)

(array([[0.99982271]]), 1)

# 다변수 함수의 logistic classification

## 1단계 : 데이터 준비

In [65]:
x_data = np.array([[2,4], [4,11], [6,6], [8,5], [10,7], [12,16], [14,8], [16,3], [18,7]])
t_data = np.array([0,0,0,0,0,1,1,1,1]).reshape(9,1)

#test_data = np.empty(18).reshape(9,2)

## 2단계 : W, b 초기화

In [63]:
#z = W1*x1 + W2*x2 + b
W = np.random.rand(2,1)
b = np.random.rand(1)

## 3단계 : 손실함수 정의

In [50]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

def loss_func(x, t):
    delta = 1e-7
    
    z = np.dot(x,W)+b
    y = sigmoid(z)
    
    return -np.sum((t*np.log(y+delta))+((1-t)*np.log(1-y+delta)))

## 4단계 : 수치미분함수 및 utility 함수 정의

In [51]:
def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    #각 변수에 대해서 편미분을 하는 부분
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val)+delta_x
        fx1 = f(x)
        
        x[idx] = float(tmp_val)-delta_x
        fx2 = f(x)
        grad[idx] = (fx1-fx2)/(2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

def error_value(x, t):
   #log값이 무한대로 발산하는 것을 방지하기 위함.
    delta = 1e-7
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    return -np.sum((t*np.log(y+delta))+((1-t)*np.log(1-y+delta)))

def predict(x):
    z = np.dot(x,W)+b
    y = sigmoid(z)
    
    if(y>0.5):
        result = 1
    else:
        result = 0
        
    return y, result

## 5단계 : 학습

In [66]:
learning_rate = 1e-2

f = lambda x : loss_func(x_data, t_data)

for step in range(80001):
    W -= learning_rate*numerical_derivative(f, W)
    b -= learning_rate*numerical_derivative(f, b)
    
    if(step % 400 == 0):
        print('[step :',step,']')
        print('error_value : ', error_value(x_data, t_data))
        print('W :\n',W,'\nb :',b,'\n')

[step : 0 ]
error_value :  0.04883328216738871
W :
 [[1.89055723]
 [0.53751775]] 
b : [-26.22464121] 

[step : 400 ]
error_value :  0.04860179332858431
W :
 [[1.89268003]
 [0.53813628]] 
b : [-26.25499736] 

[step : 800 ]
error_value :  0.04837249364065875
W :
 [[1.89479281]
 [0.53875185]] 
b : [-26.2852096] 

[step : 1200 ]
error_value :  0.04814535216316473
W :
 [[1.89689566]
 [0.53936449]] 
b : [-26.31527928] 

[step : 1600 ]
error_value :  0.047920338536561025
W :
 [[1.89898867]
 [0.53997423]] 
b : [-26.34520776] 

[step : 2000 ]
error_value :  0.0476974229686457
W :
 [[1.90107193]
 [0.5405811 ]] 
b : [-26.37499635] 

[step : 2400 ]
error_value :  0.04747657622133449
W :
 [[1.90314554]
 [0.54118511]] 
b : [-26.40464635] 

[step : 2800 ]
error_value :  0.047257769597840726
W :
 [[1.90520958]
 [0.54178631]] 
b : [-26.43415905] 

[step : 3200 ]
error_value :  0.04704097493018455
W :
 [[1.90726415]
 [0.54238471]] 
b : [-26.46353573] 

[step : 3600 ]
error_value :  0.04682616456704402
W

[step : 31200 ]
error_value :  0.03561223515661646
W :
 [[2.03172917]
 [0.57857421]] 
b : [-28.24225262] 

[step : 31600 ]
error_value :  0.035489130589283886
W :
 [[2.03327886]
 [0.57902405]] 
b : [-28.26438817] 

[step : 32000 ]
error_value :  0.035366875943551514
W :
 [[2.03482322]
 [0.57947232]] 
b : [-28.28644716] 

[step : 32400 ]
error_value :  0.03524546244187325
W :
 [[2.03636227]
 [0.57991904]] 
b : [-28.30843012] 

[step : 32800 ]
error_value :  0.03512488142721762
W :
 [[2.03789605]
 [0.58036421]] 
b : [-28.33033757] 

[step : 33200 ]
error_value :  0.03500512436100271
W :
 [[2.03942459]
 [0.58080784]] 
b : [-28.35217003] 

[step : 33600 ]
error_value :  0.03488618282107832
W :
 [[2.04094795]
 [0.58124995]] 
b : [-28.37392802] 

[step : 34000 ]
error_value :  0.03476804849974626
W :
 [[2.04246614]
 [0.58169055]] 
b : [-28.39561203] 

[step : 34400 ]
error_value :  0.034650713201820046
W :
 [[2.0439792 ]
 [0.58212963]] 
b : [-28.41722257] 

[step : 34800 ]
error_value :  0.0

[step : 63200 ]
error_value :  0.02787961324194604
W :
 [[2.14135076]
 [0.61035096]] 
b : [-29.80743379] 

[step : 63600 ]
error_value :  0.027804185749992678
W :
 [[2.14256473]
 [0.61070237]] 
b : [-29.8247599] 

[step : 64000 ]
error_value :  0.027729166156656673
W :
 [[2.14377543]
 [0.61105282]] 
b : [-29.84203908] 

[step : 64400 ]
error_value :  0.027654551160174637
W :
 [[2.14498286]
 [0.61140231]] 
b : [-29.8592716] 

[step : 64800 ]
error_value :  0.027580337494331336
W :
 [[2.14618706]
 [0.61175086]] 
b : [-29.87645771] 

[step : 65200 ]
error_value :  0.027506521927986253
W :
 [[2.14738803]
 [0.61209846]] 
b : [-29.89359765] 

[step : 65600 ]
error_value :  0.02743310126460114
W :
 [[2.14858579]
 [0.61244512]] 
b : [-29.91069168] 

[step : 66000 ]
error_value :  0.027360072341782525
W :
 [[2.14978037]
 [0.61279085]] 
b : [-29.92774004] 

[step : 66400 ]
error_value :  0.027287432030822414
W :
 [[2.15097177]
 [0.61313565]] 
b : [-29.94474297] 

[step : 66800 ]
error_value :  0

In [67]:
predict([3,17])

(array([1.65030583e-06]), 0)

In [68]:
predict([8,8])

(array([0.00034039]), 0)

In [69]:
predict([10,10])

(array([0.08651149]), 0)

In [70]:
predict([7,21])

(array([0.11320911]), 0)

In [71]:
predict(np.array([12,2]))

(array([0.04869305]), 0)

In [72]:
predict(np.array([16,3]))

(array([0.99835908]), 1)

In [78]:
predict(np.array([13,3]))

(array([0.46051822]), 0)