# 10.Logic Gate

## external function

In [1]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x)
        
        grad = (fx1-fx2)/(2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

## logic gate class

In [2]:
class LogicGate:
    ##init
    def __init__(self, gate_name, xdata, tdata):
        self.name = gate_name
        
        self.__xdata = xdata.reshape(4,2) #입력 데이터가 (00, 01, 10, 11) 4개 뿐임
        self.__tdata = tdata.reshape(4,1)
        
        self.__W = np.random.rand(2,1)
        self.__b = np.random.rand(1)
        
        self.__learning_rate = 1e-2
        
    # loss function
    def loss_func(self):
        delta = 1e-7
        
        z = np.dot(self.__xdata, self.__W)+self.__b
        y = sigmoid(z)
        
        return -np.sum(self.__tdata*np.log(y+delta) + (1-self.__tdata)*np.log((1-y)+delta))
    
    # compute loss value
    def error_val(self):
        delta = 1e-7
        
        z = np.dot(self.__xdata, self.__W)+self.__b
        y = sigmoid(z)
        
        return -np.sum(self.__tdata*np.log(y+delta) + (1-self.__tdata)*np.log((1-y)+delta))
    
    def train(self):
        f = lambda x : self.loss_func()
        print('initial error value = ', self.error_val())
        
        for step in range(10001):
            self.__W -= self.__learning_rate*numerical_derivative(f, self.__W)
            self.__b -= self.__learning_rate*numerical_derivative(f, self.__b)
            if(step % 500 == 0):
                print('step : ', step, '\terror value : ', self.error_val())
                print('W : \n', self.__W)
                print('b : ', self.__b)
                
    def predict(self, input_data):
        z = np.dot(input_data, self.__W)+self.__b
        y = sigmoid(z)
        
        if(y > 0.5):
            result = 1
        else :
            result = 0
            
        return y, result
        

## AND Gate

In [3]:
xdata = np.array([[0,0],[0,1],[1,0],[1,1]])
tdata = np.array([0,0,0,1])

AND_obj = LogicGate("AND_GATE", xdata, tdata)
AND_obj.train()

initial error value =  3.2896381361305234
step :  0 	error value :  3.2576669031755063
W : 
 [[0.61368652]
 [0.46399053]]
b :  [0.17242528]
step :  500 	error value :  1.345958796898334
W : 
 [[1.26950209]
 [1.11980611]]
b :  [-2.1363177]
step :  1000 	error value :  0.9719195799737425
W : 
 [[1.97638089]
 [1.82668491]]
b :  [-3.11509321]
step :  1500 	error value :  0.7655156173351849
W : 
 [[2.49600595]
 [2.34630997]]
b :  [-3.8596591]
step :  2000 	error value :  0.6317785326711611
W : 
 [[2.91238087]
 [2.76268488]]
b :  [-4.46562193]
step :  2500 	error value :  0.537310515205051
W : 
 [[3.26156667]
 [3.11187069]]
b :  [-4.97799125]
step :  3000 	error value :  0.4668558238971413
W : 
 [[3.56277073]
 [3.41307475]]
b :  [-5.42213506]
step :  3500 	error value :  0.4122751894190825
W : 
 [[3.82769767]
 [3.67800169]]
b :  [-5.81404598]
step :  4000 	error value :  0.36876962258174967
W : 
 [[4.0641212 ]
 [3.91442522]]
b :  [-6.16457857]
step :  4500 	error value :  0.33330630636666325

In [4]:
print(AND_obj.name, '\n')

test_data = np.array([[0,0],[0,1],[1,0],[1,1]])

for input_data in test_data:
    (sigmoid_val, logical_val) = AND_obj.predict(input_data)
    print(input_data, "=", logical_val, '( possibility : ', sigmoid_val, ')')

AND_GATE 

[0 0] = 0 ( possibility :  [0.00015544] )
[0 1] = 0 ( possibility :  [0.042818] )
[1 0] = 0 ( possibility :  [0.04939079] )
[1 1] = 1 ( possibility :  [0.93730336] )


## NAND Gate

In [11]:
xdata = np.array([[0,0],[0,1],[1,0],[1,1]])
tdata = np.array([1,1,1,0])

NAND_obj = LogicGate("NAND_GATE", xdata, tdata)
NAND_obj.train()

initial error value =  2.7795059010096503
step :  0 	error value :  2.7751927460432904
W : 
 [[0.72827272]
 [0.12842343]]
b :  [0.35614278]
step :  500 	error value :  1.6100751055221183
W : 
 [[-0.50469653]
 [-1.10454582]]
b :  [1.70338402]
step :  1000 	error value :  1.18078202909314
W : 
 [[-1.17992428]
 [-1.77977358]]
b :  [2.6103122]
step :  1500 	error value :  0.9501117857301951
W : 
 [[-1.6556007 ]
 [-2.25544999]]
b :  [3.27984938]
step :  2000 	error value :  0.8010413159901786
W : 
 [[-2.02926889]
 [-2.62911818]]
b :  [3.81692934]
step :  2500 	error value :  0.6947444199472486
W : 
 [[-2.34012483]
 [-2.93997412]]
b :  [4.26878361]
step :  3000 	error value :  0.614289606165152
W : 
 [[-2.60775977]
 [-3.20760906]]
b :  [4.66048146]
step :  3500 	error value :  0.5509122727155507
W : 
 [[-2.8434786 ]
 [-3.44332789]]
b :  [5.0070323]
step :  4000 	error value :  0.4995297360304032
W : 
 [[-3.05447428]
 [-3.65432357]]
b :  [5.3182245]
step :  4500 	error value :  0.456950726941

In [13]:
print(NAND_obj.name, '\n')

test_data = np.array([[0,0],[0,1],[1,0],[1,1]])

for input_data in test_data:
    (sigmoid_val, logical_val) = NAND_obj.predict(input_data)
    print(input_data, "=", logical_val, '( possibility : ', sigmoid_val, ')')

NAND_GATE 

[0 0] = 1 ( possibility :  [0.99954189] )
[0 1] = 1 ( possibility :  [0.91973851] )
[1 0] = 1 ( possibility :  [0.95428992] )
[1 1] = 0 ( possibility :  [0.0988111] )


## OR Gate

In [15]:
xdata = np.array([[0,0],[0,1],[1,0],[1,1]])
tdata = np.array([0,1,1,1])

OR_obj = LogicGate("OR_GATE", xdata, tdata)
OR_obj.train()

initial error value =  2.3963528769279687
step :  0 	error value :  2.3808686170277786
W : 
 [[0.04411551]
 [0.05868986]]
b :  [0.38330952]
step :  500 	error value :  1.1001466233245767
W : 
 [[1.60383518]
 [1.61840953]]
b :  [0.02794909]
step :  1000 	error value :  0.747233077556637
W : 
 [[2.44153161]
 [2.45610597]]
b :  [-0.5521755]
step :  1500 	error value :  0.5589931916868454
W : 
 [[3.06724899]
 [3.08182335]]
b :  [-0.93746723]
step :  2000 	error value :  0.4433347925795561
W : 
 [[3.56310544]
 [3.5776798 ]]
b :  [-1.22298753]
step :  2500 	error value :  0.3656719959087694
W : 
 [[3.97166951]
 [3.98624386]]
b :  [-1.44973575]
step :  3000 	error value :  0.31023650560940846
W : 
 [[4.3179463 ]
 [4.33252065]]
b :  [-1.63766844]
step :  3500 	error value :  0.2688484866071374
W : 
 [[4.61775585]
 [4.63233021]]
b :  [-1.79799744]
step :  4000 	error value :  0.2368628567536799
W : 
 [[4.88168619]
 [4.89626055]]
b :  [-1.93767854]
step :  4500 	error value :  0.2114574522034533

In [16]:
print(OR_obj.name, '\n')

test_data = np.array([[0,0],[0,1],[1,0],[1,1]])

for input_data in test_data:
    (sigmoid_val, logical_val) = OR_obj.predict(input_data)
    print(input_data, "=", logical_val, '( possibility : ', sigmoid_val, ')')

OR_GATE 

[0 0] = 0 ( possibility :  [0.05202684] )
[0 1] = 1 ( possibility :  [0.97939751] )
[1 0] = 1 ( possibility :  [0.97910137] )
[1 1] = 1 ( possibility :  [0.99997536] )


## XOR Gate

In [7]:
xdata = np.array([[0,0], [0,1],[1,0],[1,1]])
tdata = np.array([0,1,1,0])

XOR_obj = LogicGate("XOR_Gate", xdata, tdata)
XOR_obj.train()

initial error value =  2.9088683623111997
step :  0 	error value :  2.90504049291891
W : 
 [[0.12111635]
 [0.55371892]]
b :  [0.09850529]
step :  500 	error value :  2.78533673801677
W : 
 [[-0.26546321]
 [ 0.16713936]]
b :  [0.01838084]
step :  1000 	error value :  2.789250926939342
W : 
 [[-0.35621594]
 [ 0.07638664]]
b :  [0.12577501]
step :  1500 	error value :  2.792489995126843
W : 
 [[-0.39761569]
 [ 0.03498688]]
b :  [0.17483953]
step :  2000 	error value :  2.7942754044929408
W : 
 [[-0.41656122]
 [ 0.01604135]]
b :  [0.19729135]
step :  2500 	error value :  2.7951571156525166
W : 
 [[-0.42524387]
 [ 0.0073587 ]]
b :  [0.20758081]
step :  3000 	error value :  2.7955748300678547
W : 
 [[-0.42922606]
 [ 0.00337651]]
b :  [0.21229993]
step :  3500 	error value :  2.7957692816072233
W : 
 [[-0.43105309]
 [ 0.00154948]]
b :  [0.21446507]
step :  4000 	error value :  2.7958591013308136
W : 
 [[-0.43189148]
 [ 0.00071109]]
b :  [0.2154586]
step :  4500 	error value :  2.7959004451106

In [8]:
print(XOR_obj.name, '\n')

test_data = np.array([[0,0],[0,1],[1,0],[1,1]])

for input_data in test_data:
    (sigmoid_val, logical_val) = XOR_obj.predict(input_data)
    print(input_data, "=", logical_val, '( possibility : ', sigmoid_val, ')')

XOR_Gate 

[0 0] = 1 ( possibility :  [0.55386545] )
[0 1] = 1 ( possibility :  [0.55386547] )
[1 0] = 0 ( possibility :  [0.44613453] )
[1 1] = 0 ( possibility :  [0.44613454] )


XOR Gate는 결과가 나오는 빈도가 정확히 50:50이다 보니, 선형회귀의 방법으로는 학습할 수 없다.
따라서 다른 방법으로 XOR Gate를 학습해야한다

## XOR 구현 방법 : NAND, OR, AND를 이용

In [38]:
input_data = np.array([[0,0], [0,1], [1,0], [1,1]])

s1 = []
s2 = []

new_input_data = []
final_output = []

for index in range(len(input_data)):
    s1 = NAND_obj.predict(input_data[index])
    s2 = OR_obj.predict(input_data[index])
    
    #s1, s2를 새로운 입력으로 사용하기 위해서 하나의 배열에 저장
    #predict는 (x, y)형태의 값을 리턴해주기 때문에, 슬라이싱을 통해서 logical value만 new_input_data에 저장
    new_input_data.append(s1[-1])
    new_input_data.append(s2[-1])
    
    (sigmoid_val, logical_val) = AND_obj.predict(np.array(new_input_data))
    
    final_output.append(logical_val)
    new_input_data=[]
    

for index in range(len(input_data)):
    print(input_data[index], " = ", final_output[index], end='\n')
    

[0 0]  =  0
[0 1]  =  1
[1 0]  =  1
[1 1]  =  0
